#!/usr/bin/env bash
# Installs nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo 'Hello World!' | sudo tee

searchString="\tlocation / {"
stringReplace="\tlocation /redirect_me {\n https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@^$searchString@$stringReplace@" /etc/nginx/sites-available/default

# line="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
# sudo sed -i "26i $line" /etc/nginx/sites-available/default
sudo service nginx restart

#  Install nginx on web-01 server

# html="/var/www/html/index.nginx-debian.html"
# sudo apt -y update && sudo apt -y upgrade $html
# sudo apt -y install nginx
# echo "Hello World!" | sudo tee 
# sudo /etc/init.d/nginx start
# line="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
# sudo sed -i "26i $line" /etc/nginx/sites-available/default
# sudo /etc/init.d/nginx restart